### ISSUE TITLE
Please tag a release

### ISSUE THREAD

**Issue by keyneston** [vovkasm/input-source-switcher#1]
Hey,

I'm trying to get a formula submitted to homebrew to allow people to easily install this. The only way they will accept the pull request is if the release is tagged. Can you tag the current version? Thanks!

-Tarrant

Pull Request: https://github.com/Homebrew/homebrew/pull/38356

**Comment by vovkasm** [comment]
Hi @tarrant , done.
Just create release [v0.2](https://github.com/vovkasm/input-source-switcher/releases/tag/v0.2) with some small cleanups in code and docs.

Is that enough for you and I can close the issue?

**Comment by keyneston** [comment]
Perfect thanks!
